
[[dependencies]]
  branch = "master"
  name = "github.com/Sirupsen/logrus"

[[dependencies]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[dependencies]]
  branch = "master"
  name = "github.com/prometheus/common"

[[dependencies]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[dependencies]]
  name = "k8s.io/client-go"
  version = "^2.0.0"
