version: 2
jobs:
  build:
    working_directory: /go/src/github.com/weaveworks/kured
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker
      - run: go get github.com/golang/dep/cmd/dep
      - run: dep ensure
      - deploy:
          name: Build and push image
          command: |
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
            if [ -z "${CIRCLE_TAG}" ]; then
                make publish-image
            else
                make VERSION="${CIRCLE_TAG}" publish-image
            fi

workflows:
  version: 2
  build:
    jobs:
     - build:
         filters:
           tags:
             only: /.*/
