apiVersion: v1
appVersion: "1.4.0"
description: A Helm chart for kured
name: kured
version: 2.0.0
home: https://github.com/weaveworks/kured
maintainers:
  - name: dholbach
    email: daniel@weave.works
  - name: ckotzbauer
    email: christian.kotzbauer@gmail.com
sources:
  - https://github.com/weaveworks/kured
icon: https://raw.githubusercontent.com/weaveworks/kured/master/img/logo.png
