apiVersion: v1
appVersion: "1.9.1"
description: A Helm chart for kured
name: kured
version: 2.12.0
home: https://github.com/weaveworks/kured
maintainers:
  - name: ckotzbauer
    email: christian.kotzbauer@gmail.com
  - name: davidkarlsen
    email: david@davidkarlsen.com
sources:
  - https://github.com/weaveworks/kured
icon: https://raw.githubusercontent.com/weaveworks/kured/main/img/logo.png
