apiVersion: v1
appVersion: "1.5.0"
description: A Helm chart for kured
name: kured
version: 2.2.1
home: https://github.com/weaveworks/kured
maintainers:
  - name: ckotzbauer
    email: christian.kotzbauer@gmail.com
  - name: davidkarlsen
    email: david@davidkarlsen.com
sources:
  - https://github.com/weaveworks/kured
icon: https://raw.githubusercontent.com/weaveworks/kured/master/img/logo.png
