name: Verify GoReleaser config
on:
  pull_request:
    paths:
      - '.config/goreleaser.yaml'
  push:
    paths:
      - '.config/goreleaser.yaml'

jobs:
  check-goreleaser-config:
    name: Check GoReleaser config
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Check GoReleaser config
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a #v6.4.0
        with:
          version: '~> v2'
          args: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}