#This is just extra testing, for lint check, and basic installation
#Those can fail earlier than functional tests (shorter tests)
# and give developer feedback soon if they didn't test themselves
name: PR - charts
on:
  pull_request:
    paths:
      - "charts/**"
jobs:
  # We create two jobs (with a matrix) instead of one to make those parallel.
  # We don't need to conditionally check if something has changed, due to github actions
  # tackling that for us.
  # Fail-fast ensures that if one of those matrix job fail, the other one gets cancelled.
  test-chart:
    name: Test helm chart changes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        test-action:
          - lint
          - install
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      # Helm is already present in github actions, so do not re-install it
      - name: Setup chart testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Create default kind cluster
        uses: helm/kind-action@v1.1.0
        with:
          version: v0.11.0
        if: ${{ matrix.test-action == 'install' }}

      - name: Run chart tests
        run: ct ${{ matrix.test-action }} --config .github/ct.yaml

  # This doesn't re-use the ct actions, due to many limitations (auto tear down, no real testing)
  deploy-chart:
    name: Functional test of helm chart in its current state (needs published image of the helm chart)
    runs-on: ubuntu-latest
    needs: test-chart
    steps:
      - uses: actions/checkout@v2
      
      # Default name for helm/kind-action kind clusters is "chart-testing"
      - name: Create 1 node kind cluster
        uses: helm/kind-action@v1.1.0
        with:
          version: v0.11.0

      - name: Deploy kured on default namespace with its helm chart
        run: |
          # Documented in official helm doc to live on the edge
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          # Refresh bins
          hash -r
          helm install kured ./charts/kured/ --set configuration.period=1m --wait
          kubectl config set-context kind-chart-testing
          kubectl get ds --all-namespaces
          kubectl describe ds kured

      - name: Test if successful deploy
        uses: nick-invision/retry@v2.4.0
        with:
          timeout_minutes: 10
          max_attempts: 10
          retry_wait_seconds: 10
          # DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE should all be = to cluster_size
          command: "kubectl get ds kured | grep -E 'kured.*1.*1.*1.*1.*1'"